# Generated by Django 5.2.17 on 2026-09-12 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('dispatched', 'Despachada'), ('in_progress', 'En curso'), ('completed', 'Completada')], default='draft', max_length=16, verbose_name='estado')),
                ('planned_distance_km', models.FloatField(default=0.0, verbose_name='distancia planificada (km)')),
                ('planned_duration_minutes', models.FloatField(default=0.0, verbose_name='duracion planificada (min)')),
                ('planned_load', models.FloatField(default=0.0, verbose_name='carga planificada')),
                ('optimizer_metrics', models.JSONField(blank=True, default=dict, help_text='Distancia contra los baselines y tiempo de calculo, para auditar el plan.', verbose_name='metricas del optimizador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='fleet.depot', verbose_name='deposito')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='chofer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='fleet.vehicle', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ('-date', 'vehicle__code'),
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='orden')),
                ('leg_distance_km', models.FloatField(default=0.0, help_text='Desde la parada anterior (o el deposito, si es la primera).', verbose_name='distancia del tramo (km)')),
                ('eta_minutes', models.FloatField(default=0.0, help_text='Estimado del planificador, no la hora real de llegada.', verbose_name='ETA (min desde la salida)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routing.route', verbose_name='ruta')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='deliveries.stop', verbose_name='parada')),
            ],
            options={
                'verbose_name': 'parada de ruta',
                'verbose_name_plural': 'paradas de ruta',
                'ordering': ('route', 'sequence'),
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['date', 'status'], name='route_date_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('vehicle', 'date'), name='one_route_per_vehicle_day'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='unique_sequence_per_route'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop'), name='unique_stop_per_route'),
        ),
    ]
