# Generated by Django 5.2.17 on 2026-09-15 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0002_english_field_labels"),
        ("fleet", "0002_english_field_labels"),
        ("routing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={
                "ordering": ("-date", "vehicle__code"),
                "verbose_name": "route",
                "verbose_name_plural": "routes",
            },
        ),
        migrations.AlterModelOptions(
            name="routestop",
            options={
                "ordering": ("route", "sequence"),
                "verbose_name": "route stop",
                "verbose_name_plural": "route stops",
            },
        ),
        migrations.AlterField(
            model_name="route",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="route",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes",
                to="fleet.depot",
                verbose_name="depot",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="driver",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="optimizer_metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Distance against the baselines and solve time, so the plan can be audited.",
                verbose_name="optimizer metrics",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="planned_distance_km",
            field=models.FloatField(default=0.0, verbose_name="planned distance (km)"),
        ),
        migrations.AlterField(
            model_name="route",
            name="planned_duration_minutes",
            field=models.FloatField(default=0.0, verbose_name="planned duration (min)"),
        ),
        migrations.AlterField(
            model_name="route",
            name="planned_load",
            field=models.FloatField(default=0.0, verbose_name="planned load"),
        ),
        migrations.AlterField(
            model_name="route",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("dispatched", "Dispatched"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes",
                to="fleet.vehicle",
                verbose_name="vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="eta_minutes",
            field=models.FloatField(
                default=0.0,
                help_text="The planner's estimate, not the real arrival time.",
                verbose_name="ETA (min from departure)",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="leg_distance_km",
            field=models.FloatField(
                default=0.0,
                help_text="From the previous stop, or from the depot when it is the first.",
                verbose_name="leg distance (km)",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_stops",
                to="routing.route",
                verbose_name="route",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="sequence",
            field=models.PositiveIntegerField(verbose_name="sequence"),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_stops",
                to="deliveries.stop",
                verbose_name="stop",
            ),
        ),
    ]
