# Generated by Django 5.2.17 on 2026-09-15 15:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.deliveries.models


class Migration(migrations.Migration):
    dependencies = [
        ("deliveries", "0001_initial"),
        ("fleet", "0002_english_field_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryevent",
            options={
                "ordering": ("occurred_at", "id"),
                "verbose_name": "delivery event",
                "verbose_name_plural": "delivery events",
            },
        ),
        migrations.AlterModelOptions(
            name="locationping",
            options={
                "ordering": ("-recorded_at",),
                "verbose_name": "position",
                "verbose_name_plural": "positions",
            },
        ),
        migrations.AlterModelOptions(
            name="stop",
            options={
                "ordering": ("scheduled_date", "created_at"),
                "verbose_name": "stop",
                "verbose_name_plural": "stops",
            },
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="client_event_id",
            field=models.UUIDField(
                help_text="Generated by the mobile app; this is what makes resending idempotent.",
                verbose_name="client event id",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="driver",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("departed", "Departed for the stop"),
                    ("arrived", "Arrived at the stop"),
                    ("delivered", "Delivered"),
                    ("failed", "Delivery failed"),
                    ("note", "Note"),
                ],
                max_length=16,
                verbose_name="kind",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="latitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="latitude",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="longitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="longitude",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="note",
            field=models.TextField(blank=True, verbose_name="note"),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="occurred_at",
            field=models.DateTimeField(help_text="Device clock.", verbose_name="occurred at"),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("absent", "Customer not there"),
                    ("wrong_address", "Wrong address"),
                    ("refused", "Order refused"),
                    ("no_access", "No access to the site"),
                    ("other", "Other"),
                ],
                max_length=24,
                verbose_name="reason",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="received_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="received at"),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="deliveries.stop",
                verbose_name="stop",
            ),
        ),
        migrations.AlterField(
            model_name="locationping",
            name="accuracy_m",
            field=models.FloatField(blank=True, null=True, verbose_name="accuracy (m)"),
        ),
        migrations.AlterField(
            model_name="locationping",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="driver",
            ),
        ),
        migrations.AlterField(
            model_name="locationping",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="latitude",
            ),
        ),
        migrations.AlterField(
            model_name="locationping",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="longitude",
            ),
        ),
        migrations.AlterField(
            model_name="locationping",
            name="recorded_at",
            field=models.DateTimeField(verbose_name="recorded at"),
        ),
        migrations.AlterField(
            model_name="locationping",
            name="speed_kmh",
            field=models.FloatField(blank=True, null=True, verbose_name="speed (km/h)"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="address",
            field=models.CharField(max_length=255, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="customer_name",
            field=models.CharField(max_length=120, verbose_name="customer"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="demand",
            field=models.FloatField(
                default=1.0,
                help_text="Weight or volume, in the same unit as the vehicle capacity.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="demand",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stops",
                to="fleet.depot",
                verbose_name="depot",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="latitude",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="longitude",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="scheduled_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="scheduled date"
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="service_minutes",
            field=models.PositiveIntegerField(default=5, verbose_name="service time (min)"),
        ),
        migrations.AlterField(
            model_name="stop",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("planned", "Planned"),
                    ("in_transit", "In transit"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                editable=False,
                help_text="Projection of the event log. Never edited by hand.",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="tracking_code",
            field=models.CharField(
                default=apps.deliveries.models.generate_tracking_code,
                editable=False,
                max_length=16,
                unique=True,
                verbose_name="tracking code",
            ),
        ),
    ]
