# Generated by Django 5.2.17 on 2026-09-12 03:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='direccion')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitud')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitud')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'deposito',
                'verbose_name_plural': 'depositos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='codigo')),
                ('plate', models.CharField(blank=True, max_length=16, verbose_name='matricula')),
                ('capacity', models.FloatField(help_text='En la misma unidad que la demanda de las paradas.', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='capacidad')),
                ('max_shift_minutes', models.PositiveIntegerField(default=480, verbose_name='jornada maxima (min)')),
                ('avg_speed_kmh', models.FloatField(default=25.0, verbose_name='velocidad media (km/h)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet.depot', verbose_name='deposito')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=32, verbose_name='licencia')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='fleet.depot', verbose_name='deposito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('default_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_drivers', to='fleet.vehicle', verbose_name='vehiculo habitual')),
            ],
            options={
                'verbose_name': 'chofer',
                'verbose_name_plural': 'choferes',
                'ordering': ('user__username',),
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='vehicle_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('avg_speed_kmh__gt', 0)), name='vehicle_speed_positive'),
        ),
    ]
