# Generated by Django 5.2.17 on 2026-09-15 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depot',
            options={'ordering': ('name',), 'verbose_name': 'depot', 'verbose_name_plural': 'depots'},
        ),
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'ordering': ('user__username',), 'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('code',), 'verbose_name': 'vehicle', 'verbose_name_plural': 'vehicles'},
        ),
        migrations.AlterField(
            model_name='depot',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='default_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_drivers', to='fleet.vehicle', verbose_name='default vehicle'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='fleet.depot', verbose_name='depot'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='licence'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='avg_speed_kmh',
            field=models.FloatField(default=25.0, verbose_name='average speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.FloatField(help_text="In the same unit as the stops' demand.", validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet.depot', verbose_name='depot'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='max_shift_minutes',
            field=models.PositiveIntegerField(default=480, verbose_name='max shift (min)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=16, verbose_name='plate'),
        ),
    ]
